### ISSUE TITLE
Please decrease cyclomatic complexity of ASTFormer.sanitize method

### ISSUE THREAD

**Issue by tisnik** [walker76/code-duplication#2]
https://github.com/walker76/code-duplication/blob/e16821d424876fdff62c4b28a97cfe685076ba4f/stackoversight/astformer.py#L48

**Comment by johnsimmons2** [comment]
This is now Filter.filter, name may need changing, because this is used primarily to filter rather than just sanitize.

**Comment by johnsimmons2** [comment]
The new Filter.check_filter(self, item): method is much less complex and much easier to read.
