### ISSUE TITLE
Please use constant containing the file path + name, might be provided by config module

### ISSUE THREAD

**Issue by tisnik** [walker76/code-duplication#23]
https://github.com/walker76/code-duplication/blob/0c37db7afaeefc155b80f4b3ed7bb91327c00446/stackoversight/gitpickler.py#L13

**Comment by johnsimmons2** [comment]
@tisnik this file will be deprecated as soon as our permanent solution for serialization is implemented, this was just to temporarily store our API requests. But for future prototyping we will make sure to stick to guidelines such as this!

**Comment by tisnik** [comment]
Sure @johnsimmons2 . Thanks for info -> I'm closing this bug :)
